parameters:
    epochs: [10]
    steps: [10]
    repetitions: [1]
    batch_size: [128]
    name_estimator: ['aipw']
    name_base_model: ['resnet50','inceptionv3','image_regression']
    output_name: 'aipw_dl_'
    path_root: 'gs://icetea_kaggle_data/data/'
    path_tfrecords_new: 'icetea_newdata/'
    path_features: 'icetea_features/'
    path_results: 'icetea_kaggle_results/'
    bucket_name: 'icetea_kaggle_data'
