parameters:
    epochs: [25]
    steps: [20]
    repetitions: [1]
    batch_size: [64]
    name_estimator: ['aipw']
    name_base_model: ['image_regression']
    output_name: 'aipw_image_'
    path_root: 'gs://icetea_kaggle_data/data/'
    path_tfrecords_new: 'icetea_newdata/'
    path_features: 'icetea_features/'
    path_results: 'icetea_kaggle_results/'
