parameters:
    backbone_drop_rate: 0.25
    batch_size: 16
    epochs: 10
    hidden_size: 64
    input_shape: [ 128, 128 ]
    learning_rate: 0.0001
    num_classes: 5
    optimizer: 'adam'
    steps_per_epoch: 5
    xfe_proportion_size: 0.33 #  Proportion of X used for the feature extractor.
